export { default as IconMenu } from './IconMenu.vue'
export { default as IconClose } from './IconClose.vue'
export { default as IconUsers } from './IconUsers.vue'
export { default as IconChart } from './IconChart.vue'
export { default as IconSettings } from './IconSettings.vue'
export { default as IconBank } from './IconBank.vue'
export { default as IconReceipt } from './IconReceipt.vue'
